server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/may?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password: 123456
    listen-pattern: __keyevent@7__:expired


missyou:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/


wx:
  appid: fsjdladfljsdfjsd
  appsecret: fjsldafjlsdf
  code2session: testestetse



